repos:
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.950  # Specify the version of mypy
  hooks:
    - id: mypy
      files: \.py$

# - repo: https://github.com/pre-commit/mirrors-pytest
#   rev: v6.2.5  # Specify the version of pytest
#   hooks:
#     - id: pytest
#       files: tests/
